- name: Update packages  
  apt:
    upgrade: 'True'
    update_cache: 'True'

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_db }}"

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Create database user
  shell: |
    sudo mysql -u root -e "CREATE USER 'new_mysql_user1' IDENTIFIED BY 'testpassword'"
  register: output

- debug:
    msg: "{{ output }}"
- name: Create database
  shell: |
    sudo mysql -u root -e "CREATE DATABASE my_wiki1"

- name: Create new user for new database
  shell: |
    sudo mysql -u root -e "GRANT ALL ON my_wiki1.* TO 'new_mysql_user1'"
