mediawiki_src_url: "https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz"

packages_web:
    - php 
    - php-mysql 
    - php-xml 
    - php-mbstring
    - apache2
    - libapache2-mod-php