- name: Update packages  
  apt:
    upgrade: 'True'
    update_cache: 'True'

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_web }}"

- name: start web service
  systemd: state=started name=apache2 enabled=true

- name: Download the MediaWiki Binary
  get_url: 
     url: "{{ mediawiki_src_url }}"
     dest: '/tmp/mediawiki-1.31.1.tar.gz'
     mode: 0644

- name: Extract the tar
  unarchive:
    src: /tmp/mediawiki-1.31.1.tar.gz
    dest: /var/lib
    remote_src: yes

- name: Create a symlink for mediawiki
  file: 
   src: '/var/lib/mediawiki-1.31.1/'
   dest: '/var/www/html/mediawiki'
   state: link

- name: Change ownership
  command: chown -R root:root /var/www/html/mediawiki

- name: restart web service
  systemd: name=apache2 state=restarted