- name: Update packages  
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ packages_web }}"

- name: start the web server
  systemd: state=started name=httpd enabled=true

- name: Download the MediaWiki Binary
  get_url: 
     url: 'https://releases.wikimedia.org/mediawiki/1.37/mediawiki-1.37.0.tar.gz'
     dest: '/tmp/mediawiki-1.37.0.tar.gz'
     mode: 0644

- name: Extract the tar
  unarchive:
    src: /tmp/mediawiki-1.37.0.tar.gz
    dest: /var/www
    remote_src: yes

- name: create a symlink
  file: 
   src: '/var/www/mediawiki-1.37.0/'
   dest: '/var/www/mediawiki'
   state: link

- name: set permissions for apache
  command: chown -R apache:apache /var/www/mediawiki

- name: restart httpd service
  systemd: name=httpd state=restarted